### PR TITLE
Add Suggested Rooms

### PR DESCRIPTION
**Pull request by CodeLikeCrazE**
I added... well, suggested rooms. That's all.

### CODE REVIEW

**Review by micahlt — CHANGES_REQUESTED** [review]
This looks great!  However, let's add balloon CSS that explains what each of the rooms is.  :)

**Comment by CodeLikeCrazE** [comment]
> This looks great! However, let's add balloon CSS that explains what each of the rooms is. :)

I have no idea how to do ballon CSS. lol. Can you explain it?

**Comment by micahlt** [comment]
@CodeLikeCrazE https://kazzkiq.github.io/balloon.css/

**Comment by CodeLikeCrazE** [comment]
I already added Balloon CSS lol.

**Comment by micahlt** [comment]
Ah!  In that case, let me resolve the changes and merge 😁

**Comment by micahlt** [comment]
@CodeLikeCrazE I appreciate the PR but I'm actually in the process of completely rebuilding the UI to be more modern, so it'll be easier if I just implement suggested rooms while I'm doing that.  Thanks!

**Pull request closed without merging**
