### PR TITLE
Fix Crashing

### PR DESCRIPTION
**Pull request by CodeLikeCrazE**
I fixed the crashing vulnerability that just about everybody and their cousin has performed. _wait are these supposed to be formal_

### CODE REVIEW

**Comment by Semisol** [comment]
empty images crash servers i found that out along with "ban"

**Comment by CodeLikeCrazE** [comment]
> empty images crash servers i found that out along with "ban"

BTW, ban crash has existed for a while. Though empty images is a pretty cool tactic!

**Comment by Semisol** [comment]
> > empty images crash servers i found that out along with "ban"
> 
> BTW, ban crash has existed for a while. Though empty images is a pretty cool tactic!

Yeah, the `undefined` split is the problem

**Comment by micahlt** [comment]
Looks good!  Thank you.

**Pull request merged**
